- name: Install required libraries
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - libgtk2.0-0
    - libxtst6
    - libxss1
    - libgconf-2-4
    - libnss3
    - libasound2
